version: "3"
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    hostname: clickhouse-server
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
      - "9004:9004"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    expose:
      - "9000"
